In [3]:
import pandas as pd
import numpy as np

np.random.seed(42)

months = pd.date_range('2024-01-01', '2024-12-31', freq='D')
categories = ['Electronics', 'Clothing', 'Groceries', 'Furniture', 'Toys']

data = []

for month in months:
    for category in categories:
        data.append({
            'month': month,
            'category': category,
            'sales': np.random.randint(5000, 20000),
            'profit': np.random.uniform(0.1, 0.4)
        })
ecom_df = pd.DataFrame(data)
print(ecom_df)

          month     category  sales    profit
0    2024-01-01  Electronics  12270  0.338963
1    2024-01-01     Clothing  10390  0.319598
2    2024-01-01    Groceries  16964  0.279055
3    2024-01-01    Furniture  11265  0.146798
4    2024-01-01         Toys   9426  0.237775
...         ...          ...    ...       ...
1825 2024-12-31  Electronics   8619  0.207109
1826 2024-12-31     Clothing   8583  0.265597
1827 2024-12-31    Groceries   8326  0.290309
1828 2024-12-31    Furniture  19039  0.342424
1829 2024-12-31         Toys   9967  0.354413

[1830 rows x 4 columns]

In [20]:
np.random.seed(24)

employees = 200
employees_data = ({
    'employee_id': range(1, employees + 1),
    'department': np.random.choice(['Sales', 'Marketing', 'IT', 'HR', 'Finance'], employees),
    'salary': np.random.randint(40000, 120000, employees),
    'age': np.random.randint(22, 60, employees)
})

employees_data['experience_years(this company)'] = [np.random.randint(0, max(1, age - 21)) for age in employees_data['age']]

employees_df = pd.DataFrame(employees_data)
print(employees_df.to_string(index=False))

 employee_id department  salary  age  experience_years(this company)
           1         IT   90401   38                               4
           2         HR   53739   30                               4
           3      Sales   82401   39                              13
           4  Marketing   61094   57                               6
           5  Marketing   98592   51                              17
           6  Marketing   49054   39                               4
           7    Finance   93567   38                               5
           8         HR  105609   42                               8
           9    Finance   87312   33                               4
          10         HR   50983   39                               0
          11         IT  103580   29                               6
          12         HR  104540   54                              14
          13         HR   55371   32                               3
          14         HR   45987   35                               4
          15         HR   99455   56                              26
          16  Marketing   49581   41                              16
          17         IT   63479   44                              10
          18  Marketing   85580   56                               9
          19         HR  116329   40                               6
          20    Finance   54961   59                              12
          21      Sales   97997   49                              16
          22    Finance   58570   26                               0
          23  Marketing   52795   48                              19
          24  Marketing   61109   53                              10
          25    Finance   83885   56                              12
          26  Marketing   89477   27                               5
          27  Marketing  105417   34                               7
          28  Marketing   43179   56                              10
          29  Marketing  109773   38                               2
          30         IT   76255   41                              18
          31         HR   59742   50                              14
          32      Sales  107915   28                               3
          33         IT   51839   54                              15
          34         HR   65574   43                              17
          35  Marketing   44472   26                               2
          36  Marketing  119540   27                               1
          37         HR  118475   37                               2
          38    Finance   80598   54                              26
          39  Marketing   75105   35                              13
          40         IT  109200   42                               2
          41  Marketing   63309   30                               1
          42      Sales   63719   45                               0
          43    Finance  108802   51                               3
          44         HR   62439   56                              11
          45         IT   44343   23                               1
          46      Sales   96298   40                              16
          47  Marketing   89123   33                               3
          48      Sales  119694   22                               0
          49         HR  117142   26                               2
          50         IT  100050   49                              15
          51         HR   41977   55                               0
          52    Finance   41050   49                               7
          53      Sales  115012   50                               5
          54      Sales  110057   30                               0
          55         IT   47194   50                               4
          56         HR   60631   44                               4
          57    Finance  111763   58                              20
          58         HR   86957   41                              10
          59         HR   81380   23                               1
          60      Sales   66807   46                               0
          61         HR   73975   57                               7
          62  Marketing   71622   59                               2
          63         IT  108988   40                               7
          64         IT   66772   49                               9
          65  Marketing  100711   34                               0
          66         HR   79164   32                               7
          67      Sales   74863   37                              15
          68         HR   68125   22                               0
          69         IT   92392   45                              16
          70  Marketing   48892   48                              14
          71      Sales   63659   25                               2
          72         IT   57889   33                              11
          73      Sales   66786   55                              24
          74         IT   46811   33                               9
          75      Sales  110019   44                               1
          76         IT   95491   53                              12
          77      Sales   87724   37                              13
          78    Finance   76280   37                               3
          79         HR   96855   43                               0
          80    Finance   92897   33                               1
          81         IT  114567   49                              20
          82    Finance   63586   48                              13
          83         HR   98126   31                               0
          84    Finance  106539   48                              13
          85    Finance   63326   48                               0
          86    Finance   90854   42                               8
          87         HR   47847   52                              24
          88         IT   78039   59                              11
          89         IT   82191   44                               0
          90         HR   95684   35                               8
          91      Sales   74373   27                               4
          92    Finance   60159   27                               0
          93         HR  112849   37                               0
          94      Sales  115651   25                               1
          95         IT   97504   57                              14
          96  Marketing   65024   42                              17
          97      Sales   97825   48                              12
          98         IT   55546   36                               2
          99      Sales   65522   24                               1
         100    Finance   79878   44                              21
         101    Finance   81337   41                              13
         102    Finance   76289   40                              17
         103    Finance   92875   37                               1
         104         HR  107767   51                              19
         105    Finance  109170   59                               8
         106  Marketing  101667   36                              12
         107      Sales   63598   28                               5
         108         HR  115178   38                               1
         109    Finance   49242   42                               9
         110  Marketing   71784   41                               0
         111  Marketing   94712   43                               1
         112    Finance   85476   47                              12
         113    Finance   57744   51                               9
         114         IT   79442   40                              13
         115         IT   60808   46                               6
         116         HR   88136   23                               0
         117  Marketing   65021   58                              35
         118         IT  101915   50                               2
         119  Marketing   78172   23                               1
         120      Sales   53805   33                               1
         121  Marketing   44098   48                              11
         122         IT  109918   46                               6
         123    Finance  111247   44                               1
         124         HR  112359   25                               2
         125      Sales   62832   47                               9
         126  Marketing   87117   30                               7
         127  Marketing  119099   47                               4
         128         IT   97059   46                              21
         129    Finance   71084   37                               7
         130         IT   48903   51                              26
         131      Sales   99634   29                               3
         132    Finance   75056   46                              14
         133         HR   44674   56                              11
         134      Sales   93605   35                              11
         135         IT   92928   37                              13
         136      Sales   46201   29                               4
         137  Marketing   64695   26                               4
         138  Marketing   50299   58                               5
         139      Sales  102645   29                               7
         140         HR   58152   32                               4
         141         HR  105487   43                              19
         142      Sales   40839   30                               1
         143    Finance   88476   40                               4
         144    Finance   75412   46                               3
         145         IT   98459   37                              15
         146         IT  100607   50                              23
         147         HR   69166   45                              22
         148      Sales   86299   33                               7
         149      Sales   41403   34                               3
         150         IT   61986   52                               6
         151  Marketing   74090   35                               5
         152    Finance   59926   30                               5
         153         HR   91500   30                               7
         154      Sales   96392   34                               7
         155      Sales   61131   32                               5
         156      Sales   76139   51                               5
         157      Sales   79061   36                               8
         158    Finance   96999   50                               0
         159         HR  109612   47                              14
         160  Marketing   45359   44                               1
         161      Sales   61831   23                               1
         162  Marketing   87097   41                               9
         163         HR   88761   23                               1
         164    Finance   75954   37                               6
         165         IT   53277   38                               1
         166  Marketing  101248   22                               0
         167  Marketing  102306   22                               0
         168         IT  102273   40                              16
         169         HR  117583   55                               2
         170         IT   95614   33                               8
         171  Marketing  117764   53                              17
         172         HR   86032   29                               0
         173         IT  112596   59                              36
         174         IT   96334   50                              12
         175         IT   69501   22                               0
         176         HR   73867   47                              21
         177  Marketing   88087   49                               9
         178  Marketing   84328   53                               1
         179      Sales  103535   31                               2
         180  Marketing   69885   24                               2
         181         IT  104823   22                               0
         182  Marketing   97540   31                               2
         183      Sales   61655   56                               9
         184         HR   66099   24                               1
         185      Sales  101780   46                               4
         186         IT  116938   49                              26
         187         HR  115865   51                               1
         188    Finance   70869   38                               0
         189      Sales   55927   40                               1
         190         IT   41009   58                              26
         191         IT   64140   33                               8
         192      Sales  109232   50                              20
         193  Marketing   56388   46                               9
         194      Sales  106405   40                              10
         195    Finance   93011   59                               8
         196         HR   91473   44                              10
         197      Sales  118064   53                              25
         198  Marketing   74256   50                               4
         199         HR   59000   52                               9
         200         IT   89230   46                               8